#!/usr/bin/env php
<?php
/**
 * st、生产环境执行：
 * php /data/service/www/blog/artisan schedule:run 1>> /dev/null 2>&1
 * 个人开发环境执行示例：
 * cd /data1/www/chengjinsheng/blog/
 * php artisan schedule:run 1>> /dev/null 2>&1
 */
require_once __DIR__ . '/bootstrap/artisan_autoload.php';

$consoleCfgObj = \CjsConsole\ConsoleConfig::getInstance()->setEnvironments(env('APP_ENV', 'dev'))->setDebug(true);
if(env('APP_ENV', 'dev') != 'dev') {
    $consoleCfgObj->setCrontabEntryPath(__DIR__ . '/')->setPrefixArtisan(" artisan ");
} else {
    $consoleCfgObj->setCrontabEntryPath(__DIR__ . '/');
}

$input = new \CjsConsole\Input\ArgvInput();
$ConsoleObj = \CjsConsole\ConsoleApp::getInstance("cjs console", '1.0.0');
$kernel = new \App\Console\Kernel($ConsoleObj);

$scheduleObj = new \CjsConsole\Scheduling\ScheduleRunCommand($ConsoleObj->getSchedule());
$ConsoleObj->add($scheduleObj);

$status = $kernel->handle($input, new \CjsConsole\Output\ConsoleOutput());
$kernel->terminate($input, $status);
exit($status);